name: hafalq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  http: ^0.13.5
  intl: ^0.18.0
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.4
  flutter_svg: ^2.0.9
  hijri: ^3.0.0
  flutter_qiblah: ^3.0.3
  flutter_compass: ^0.8.1
  hijri_calendar: ^1.0.7+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true

